
import { setup, check_log } from './setup'
describe('Contact', function () {
    const anon = { email: 'epdarnell+anon@gmail.com', name: 'Cypress Testing' }
    const tester = { id: 156, email: 'epdarnell+test@gmail.com', name: 'test', password: 'testing' }
    //let freemaths = { id: 1, email: 'ed.darnell@freemaths.uk', name: 'FreeMaths.uk' }
    const ed = { id: 1, email: 'ed.darnell@freemaths.uk', name: 'Ed Darnell' }
    let link = ''
    it("Contact anon", function () {
        console.log('Contact', "Contact anon")
        setup(cy)
        cy.get('#contact').click()
        cy.get('div[name=contact]').should('contain', 'Contact FreeMaths.uk')
        cy.get('form[name=mail]').within(() => {
            cy.get('#mail_name').should(n => {
                expect(n.get(0).checkValidity()).to.equal(false)
                expect(n.get(0).validationMessage).to.equal('Please fill in this field.')
            })
            cy.get('#mail_email').should(n => {
                expect(n.get(0).checkValidity()).to.equal(false)
                expect(n.get(0).validationMessage).to.equal('Please fill in this field.')
            })
            cy.get('#mail_message').should(n => {
                expect(n.get(0).checkValidity()).to.equal(false)
                expect(n.get(0).validationMessage).to.equal('Please fill in this field.')
            })
            cy.get('#mail_name').type(anon.name)
            cy.get('#mail_email').type('invalidemail@e')
            cy.get('#mail_message').type('_test_contact_anon Cypress Test Message')
            cy.get('#mail_contact').click()
            cy.get('div[name=error_email]').should('contain', 'invalid')
            cy.get('#mail_email').clear().type(anon.email)
            cy.get('#mail_contact').click()
            //cy.get('div[name=message]').should('contain','Sending.')
        })
        cy.get('div[name=alert]', { timeout: 12000 }).should('contain', 'Message sent.') // first message can be slow
        cy.get('#test_link').invoke('text').then(l => link = l)
        cy.get('#contact').click()
        cy.get('div[name=contact]').find('button[class=btn-close]').click({ force: true })
        cy.get('div[name=alert]').should('not.exist');
        check_log(cy)
    })
    it("Check contact anon", function () {
        console.log('Contact', "Check contact anon")
        check_log(cy)
        cy.visit('/?mail=' + link, { onBeforeLoad: (win) => { win.fetch = null } })
        link = '' // will be reset at end
        cy.get('div[name=mail]').contains('Message from ' + anon.name)
        cy.get('div[name=mail]').contains('_test_contact_anon Cypress Test Message')
        cy.get('button[name=reply]').contains('Reply').click()
        cy.get('div[name=contact]').contains('Reply to ' + anon.name)
        cy.get('#mail_message').should(n => {
            expect(n.get(0).checkValidity()).to.equal(false)
            expect(n.get(0).validationMessage).to.equal('Please fill in this field.')
        })
        cy.get('#mail_edit').click()
        cy.get('textarea[id=mail_message]').should('contain', '_test_contact_anon Cypress Test Message')
        cy.get('#mail_maths').click()
        cy.get('textarea[id=mail_message]').clear().type("'_test_reply_anon y=x^3/z^4")
        cy.get('#mail_contact').contains('Reply').click()
        //cy.get('div[name=message]').should('contain','Sending...')
        cy.get('div[name=alert]', { timeout: 8000 }).should('contain', 'Message sent.')
        cy.get('#test_link').invoke('text').then(l => link = l)
        check_log(cy)
    })
    it("Check reply anon", function () {
        console.log('Contact', "Check reply anon")
        check_log(cy)
        cy.visit('/?mail=' + link, { onBeforeLoad: (win) => { win.fetch = null } })
        link = ''
        cy.get('div[name=mail]').contains('Message from ' + ed.name)
        cy.get('div[name=mail]').contains('span', '_test_reply_anon')
        cy.get('button[name=reply]').contains('Reply').click()
        cy.get('div[name=contact]').contains('Reply to ' + ed.name)
        cy.get('#mail_message').should(n => {
            expect(n.get(0).checkValidity()).to.equal(false)
            expect(n.get(0).validationMessage).to.equal('Please fill in this field.')
        })
        cy.get('#mail_edit').click()
        cy.get('textarea[id=mail_message]').should('contain', '_test_reply_anon')
        cy.get('#mail_maths').should('be.checked').click().should('not.be.checked')
        cy.get('textarea[id=mail_message]').clear().type("_test_reply_reply")
        cy.get('#mail_contact').contains('Reply').click()
        cy.get('div[name=alert]', { timeout: 8000 }).should('contain', 'Message sent.')
        cy.get('#test_link').invoke('text').then(l => link = l)
        check_log(cy)
    })
    it("Check reply reply", function () {
        console.log('Contact', "Check reply reply")
        check_log(cy)
        cy.visit('/?mail=' + link, { onBeforeLoad: (win) => { win.fetch = null } })
        cy.get('div[name=mail]').contains('Message from ' + anon.name)
        cy.get('div[name=mail]').contains('_test_reply_reply')
        check_log(cy)
    })
    it("Contact from test", function () {
        console.log('Contact', "Contact from test")
        setup(cy, tester)
        cy.get('#user').should('contain', tester.name).click()
        cy.get('#contact').click()
        cy.get('div[name=contact]').should('contain', 'Contact FreeMaths.uk')
        cy.get('div[id=mail_name]').should('not.exist')
        cy.get('#mail_message').should(n => {
            expect(n.get(0).checkValidity()).to.equal(false)
            expect(n.get(0).validationMessage).to.equal('Please fill in this field.')
        })
        cy.get('textarea[id=mail_message]').type('_test_from_test')
        cy.get('#mail_contact').click()
        cy.get('div[name=alert]', { timeout: 8000 }).should('contain', 'Message sent.')
        cy.get('#test_link').invoke('text').then(l => link = l)
        check_log(cy)
    })
    it("Check contact from tester", function () {
        console.log('Contact', "Check contact from tester")
        check_log(cy)
        cy.visit('/?mail=' + link, { onBeforeLoad: (win) => { win.fetch = null } })
        link = ''
        cy.get('div[name=mail]').contains('Message from ' + tester.name)
        cy.get('div[name=mail]').contains('_test_from_test')
        cy.get('button[name=reply]').contains('Reply').click()
        cy.get('div[name=contact]').contains('Reply to ' + tester.name)
        cy.get('#mail_message').should(n => {
            expect(n.get(0).checkValidity()).to.equal(false)
            expect(n.get(0).validationMessage).to.equal('Please fill in this field.')
        })
        cy.get('#mail_edit').click()
        cy.get('textarea[id=mail_message]').should('contain', '_test_from_test')
        cy.get('#mail_maths').should('not.be.checked').click().should('be.checked')
        cy.get('textarea[id=mail_message]').clear().type("'_test_from_test_reply y=x^3/z^4")
        cy.get('#mail_contact').contains('Reply').click()
        cy.get('div[name=alert]', { timeout: 8000 }).should('contain', 'Message sent.')
        cy.get('#test_link').invoke('text').then(l => link = l)
        check_log(cy)
    })
    it("Check reply tester", function () {
        console.log('Contact', "Check reply tester")
        check_log(cy)
        cy.visit('/?mail=' + link, { onBeforeLoad: (win) => { win.fetch = null } })
        link = ''
        cy.get('div[name=mail]').contains('Message from ' + ed.name)
        cy.get('div[name=mail]').contains('span', '_test_from_test_reply')
        cy.get('button[name=reply]').contains('Reply').click()
        cy.get('div[name=contact]').contains('Reply to ' + ed.name)
        cy.get('#mail_message').should(n => {
            expect(n.get(0).checkValidity()).to.equal(false)
            expect(n.get(0).validationMessage).to.equal('Please fill in this field.')
        })
        cy.get('#mail_edit').click()
        cy.get('textarea[id=mail_message]').should('contain', '_test_from_test_reply')
        cy.get('#mail_maths').should('be.checked').click().should('not.be.checked')
        cy.get('textarea[id=mail_message]').clear().type("_test_from_test_reply_reply")
        cy.get('#mail_contact').contains('Reply').click()
        cy.get('div[name=alert]', { timeout: 8000 }).should('contain', 'Message sent.')
        cy.get('#test_link').invoke('text').then(l => link = l)
        check_log(cy)
    })
    it("Check tester reply reply", function () {
        console.log('Contact', "Check tester reply reply")
        check_log(cy)
        cy.visit('/?mail=' + link, { onBeforeLoad: (win) => { win.fetch = null } })
        link = ''
        cy.get('div[name=mail]').contains('Message from ' + tester.name)
        cy.get('div[name=mail]').contains('_test_from_test_reply_reply')
        cy.get('div[name=mail]').find('button[class=btn-close]').click({ force: true })
        cy.get('div[name=mail]').should('not.exist')
        cy.get('#Home').contains('h5', 'Login')
        check_log(cy)
    })
})
